/**
 * nexuscli boot - Termux boot integration
 */

const chalk = require('chalk');
const fs = require('fs');

const { isInitialized, getConfig, setConfigValue } = require('../config/manager');
const { PATHS, ensureBootDirectory } = require('../utils/paths');
const { isTermux } = require('../utils/termux');

/**
 * Boot script content
 */
function generateBootScript(config) {
  const port = config.server?.port || 41800;

  return `#!/data/data/com.termux/files/usr/bin/bash
# NexusCLI Auto-Start
# Generated by: nexuscli boot enable

# Acquire wake lock to keep CPU active
termux-wake-lock

# Wait for network initialization
sleep 3

# Start NexusCLI daemon
nexuscli start --daemon

# Send notification
termux-notification \\
  --id nexuscli \\
  --title "NexusCLI" \\
  --content "Server running on port ${port}" \\
  --priority high
`;
}

/**
 * Enable boot start
 */
function enableBoot(config) {
  ensureBootDirectory();

  const script = generateBootScript(config);
  fs.writeFileSync(PATHS.BOOT_SCRIPT, script);
  fs.chmodSync(PATHS.BOOT_SCRIPT, 0o755);

  setConfigValue('termux.boot_start', true);

  return true;
}

/**
 * Disable boot start
 */
function disableBoot() {
  try {
    if (fs.existsSync(PATHS.BOOT_SCRIPT)) {
      fs.unlinkSync(PATHS.BOOT_SCRIPT);
    }
    setConfigValue('termux.boot_start', false);
    return true;
  } catch {
    return false;
  }
}

/**
 * Check boot status
 */
function getBootStatus() {
  const scriptExists = fs.existsSync(PATHS.BOOT_SCRIPT);
  const config = getConfig();
  const configEnabled = config.termux?.boot_start === true;

  return {
    enabled: scriptExists && configEnabled,
    scriptExists,
    configEnabled,
    scriptPath: PATHS.BOOT_SCRIPT
  };
}

/**
 * Main boot command
 */
async function boot(action) {
  console.log('');

  // Check Termux
  if (!isTermux()) {
    console.log(chalk.yellow('Boot integration is only available on Termux.'));
    console.log('');
    return;
  }

  if (!isInitialized()) {
    console.log(chalk.yellow('NexusCLI is not configured.'));
    console.log(`Run ${chalk.cyan('nexuscli init')} first.`);
    console.log('');
    return;
  }

  const config = getConfig();

  // Enable
  if (action === 'enable') {
    if (enableBoot(config)) {
      console.log(chalk.green('  ✓ Boot auto-start enabled'));
      console.log(chalk.gray(`  Script: ${PATHS.BOOT_SCRIPT}`));
      console.log('');
      console.log(chalk.cyan('  Make sure Termux:Boot app is installed from F-Droid'));
    } else {
      console.log(chalk.red('  ✗ Failed to enable boot'));
    }
    console.log('');
    return;
  }

  // Disable
  if (action === 'disable') {
    if (disableBoot()) {
      console.log(chalk.green('  ✓ Boot auto-start disabled'));
    } else {
      console.log(chalk.red('  ✗ Failed to disable boot'));
    }
    console.log('');
    return;
  }

  // Status
  if (action === 'status') {
    const status = getBootStatus();

    console.log(chalk.bold('Boot Status:'));
    console.log('');

    if (status.enabled) {
      console.log(chalk.green('  ✓ Auto-start is ENABLED'));
    } else {
      console.log(chalk.yellow('  ○ Auto-start is DISABLED'));
    }

    console.log('');
    console.log(`  Script exists: ${status.scriptExists ? chalk.green('yes') : chalk.gray('no')}`);
    console.log(`  Config enabled: ${status.configEnabled ? chalk.green('yes') : chalk.gray('no')}`);

    if (status.scriptExists) {
      console.log(chalk.gray(`  Path: ${status.scriptPath}`));
    }

    console.log('');
    console.log(chalk.cyan('  Requirements:'));
    console.log('    1. Termux:Boot app installed from F-Droid');
    console.log('    2. Boot script in ~/.termux/boot/');
    console.log('    3. Battery optimization disabled for Termux');
    console.log('');
    return;
  }

  // Unknown action
  console.log(chalk.red(`Unknown action: ${action}`));
  console.log('Usage:');
  console.log('  nexuscli boot enable    Enable auto-start');
  console.log('  nexuscli boot disable   Disable auto-start');
  console.log('  nexuscli boot status    Show status');
  console.log('');
}

module.exports = boot;
